server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eduardosalvarenga/proj-config
          username: ${USER}
          password: ${PASS}
          default-label: main